package com.newbulaco.showdown.api;

import com.newbulaco.showdown.api.content.*;
import com.newbulaco.showdown.api.registry.ContentRegistry;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Collection;
import java.util.List;

public final class ShowdownScriptBuilder {
    private static final Logger LOGGER = LoggerFactory.getLogger("CobblemonShowdown");

    private ShowdownScriptBuilder() {}

    public static void buildAndWriteScripts(Path modDir) {
        if (!ContentRegistry.hasShowdownJs()) {
            LOGGER.debug("No custom content with Showdown JS registered, skipping script generation");
            return;
        }

        try {
            Files.createDirectories(modDir);

            String abilitiesJs = buildAbilitiesJs();
            String movesJs = buildMovesJs();
            String conditionsJs = buildConditionsJs();

            if (!abilitiesJs.isEmpty()) {
                Files.writeString(modDir.resolve("abilities.js"), abilitiesJs);
                LOGGER.info("Wrote custom abilities.js");
            }

            if (!movesJs.isEmpty()) {
                Files.writeString(modDir.resolve("moves.js"), movesJs);
                LOGGER.info("Wrote custom moves.js");
            }

            if (!conditionsJs.isEmpty()) {
                Files.writeString(modDir.resolve("conditions.js"), conditionsJs);
                LOGGER.info("Wrote custom conditions.js");
            }

        } catch (IOException e) {
            LOGGER.error("Failed to write Showdown scripts", e);
        }
    }

    public static String buildAbilitiesJs() {
        Collection<CustomAbility> abilities = ContentRegistry.getAllAbilities();
        Collection<AbilityModification> mods = ContentRegistry.getAllAbilityModifications();
        List<String> helperJs = ContentRegistry.getAllHelperJs();

        StringBuilder sb = new StringBuilder();
        sb.append("'use strict';\n\n");
        sb.append("// Auto-generated by Cobblemon Showdown API\n\n");

        for (String helper : helperJs) {
            sb.append(helper).append("\n\n");
        }

        sb.append("exports.Abilities = {\n");

        boolean first = true;

        for (CustomAbility ability : abilities) {
            if (!ability.hasShowdownJs()) continue;

            if (!first) sb.append(",\n");
            first = false;

            sb.append("    // from ").append(ability.getModId()).append("\n");
            sb.append("    ").append(ability.getId()).append(": {\n");
            sb.append("        num: ").append(ability.getNum()).append(",\n");
            sb.append("        name: \"").append(escapeJs(ability.getDisplayName())).append("\",\n");
            sb.append("        desc: \"").append(escapeJs(ability.getDescription())).append("\",\n");
            sb.append("        ").append(ability.getShowdownJs()).append("\n");
            sb.append("    }");
        }

        for (AbilityModification mod : mods) {
            if (!mod.hasShowdownJs()) continue;

            if (!first) sb.append(",\n");
            first = false;

            sb.append("    // modification from ").append(mod.getModId()).append("\n");
            sb.append("    ").append(mod.getAbilityId()).append(": {\n");
            sb.append("        inherit: true,\n");

            if (mod.getDescription() != null) {
                sb.append("        desc: \"").append(escapeJs(mod.getDescription())).append("\",\n");
            }
            if (mod.getShortDesc() != null) {
                sb.append("        shortDesc: \"").append(escapeJs(mod.getShortDesc())).append("\",\n");
            }

            sb.append("        ").append(mod.getShowdownJs()).append("\n");
            sb.append("    }");
        }

        sb.append("\n};\n");

        return first ? "" : sb.toString();
    }

    public static String buildMovesJs() {
        Collection<CustomMove> moves = ContentRegistry.getAllMoves();
        Collection<MoveModification> mods = ContentRegistry.getAllMoveModifications();
        List<String> helperJs = ContentRegistry.getAllHelperJs();

        StringBuilder sb = new StringBuilder();
        sb.append("'use strict';\n\n");
        sb.append("// Auto-generated by Cobblemon Showdown API\n\n");

        // helpers are shared with abilities.js but may also be needed in moves.js context
        for (String helper : helperJs) {
            sb.append(helper).append("\n\n");
        }

        sb.append("exports.Moves = {\n");

        boolean first = true;

        for (CustomMove move : moves) {
            if (!move.hasShowdownJs()) continue;

            if (!first) sb.append(",\n");
            first = false;

            sb.append("    // from ").append(move.getModId()).append("\n");
            sb.append("    ").append(move.getId()).append(": {\n");
            sb.append("        num: ").append(move.getNum()).append(",\n");
            sb.append("        name: \"").append(escapeJs(move.getDisplayName())).append("\",\n");
            sb.append("        type: \"").append(move.getType()).append("\",\n");
            sb.append("        category: \"").append(move.getCategory()).append("\",\n");
            sb.append("        basePower: ").append(move.getPower()).append(",\n");
            sb.append("        accuracy: ").append(move.getAccuracy()).append(",\n");
            sb.append("        pp: ").append(move.getPp()).append(",\n");
            sb.append("        priority: ").append(move.getPriority()).append(",\n");
            sb.append("        target: \"").append(move.getTarget()).append("\",\n");

            if (!move.getFlags().isEmpty()) {
                sb.append("        flags: {");
                boolean firstFlag = true;
                for (String flag : move.getFlags()) {
                    if (!firstFlag) sb.append(", ");
                    firstFlag = false;
                    sb.append(flag).append(": 1");
                }
                sb.append("},\n");
            }

            sb.append("        desc: \"").append(escapeJs(move.getDescription())).append("\",\n");
            sb.append("        ").append(move.getShowdownJs()).append("\n");
            sb.append("    }");
        }

        for (MoveModification mod : mods) {
            if (!mod.hasShowdownJs()) continue;

            if (!first) sb.append(",\n");
            first = false;

            sb.append("    // modification from ").append(mod.getModId()).append("\n");
            sb.append("    ").append(mod.getMoveId()).append(": {\n");
            sb.append("        inherit: true,\n");

            if (mod.getPower() != null) {
                sb.append("        basePower: ").append(mod.getPower()).append(",\n");
            }
            if (mod.getAccuracy() != null) {
                sb.append("        accuracy: ").append(mod.getAccuracy()).append(",\n");
            }
            if (mod.getPp() != null) {
                sb.append("        pp: ").append(mod.getPp()).append(",\n");
            }
            if (mod.getPriority() != null) {
                sb.append("        priority: ").append(mod.getPriority()).append(",\n");
            }
            if (mod.getDescription() != null) {
                sb.append("        desc: \"").append(escapeJs(mod.getDescription())).append("\",\n");
            }

            sb.append("        ").append(mod.getShowdownJs()).append("\n");
            sb.append("    }");
        }

        sb.append("\n};\n");

        return first ? "" : sb.toString();
    }

    public static String buildConditionsJs() {
        Collection<CustomVolatileEffect> volatiles = ContentRegistry.getAllVolatileEffects();
        Collection<CustomSideCondition> sideConditions = ContentRegistry.getAllSideConditions();
        Collection<CustomFieldCondition> fieldConditions = ContentRegistry.getAllFieldConditions();

        StringBuilder sb = new StringBuilder();
        sb.append("'use strict';\n\n");
        sb.append("// Auto-generated by Cobblemon Showdown API\n\n");
        sb.append("exports.Conditions = {\n");

        boolean first = true;

        for (CustomVolatileEffect effect : volatiles) {
            if (!effect.hasShowdownJs()) continue;

            if (!first) sb.append(",\n");
            first = false;

            sb.append("    // volatile from ").append(effect.getModId()).append("\n");
            sb.append("    ").append(effect.getId()).append(": {\n");
            sb.append("        name: \"").append(escapeJs(effect.getDisplayName())).append("\",\n");
            sb.append("        ").append(effect.getShowdownJs()).append("\n");
            sb.append("    }");
        }

        for (CustomSideCondition condition : sideConditions) {
            if (!condition.hasShowdownJs()) continue;

            if (!first) sb.append(",\n");
            first = false;

            sb.append("    // side condition from ").append(condition.getModId()).append("\n");
            sb.append("    ").append(condition.getId()).append(": {\n");
            sb.append("        name: \"").append(escapeJs(condition.getDisplayName())).append("\",\n");
            sb.append("        ").append(condition.getShowdownJs()).append("\n");
            sb.append("    }");
        }

        for (CustomFieldCondition fieldCondition : fieldConditions) {
            if (!fieldCondition.hasShowdownJs()) continue;

            if (!first) sb.append(",\n");
            first = false;

            sb.append("    // field condition from ").append(fieldCondition.getModId()).append("\n");
            sb.append("    ").append(fieldCondition.getId()).append(": {\n");
            sb.append("        name: \"").append(escapeJs(fieldCondition.getDisplayName())).append("\",\n");
            sb.append("        ").append(fieldCondition.getShowdownJs()).append("\n");
            sb.append("    }");
        }

        sb.append("\n};\n");

        return first ? "" : sb.toString();
    }

    private static String escapeJs(String str) {
        if (str == null) return "";
        return str.replace("\\", "\\\\")
                  .replace("\"", "\\\"")
                  .replace("\n", "\\n")
                  .replace("\r", "");
    }
}
